"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { mutate } from "@/lib/mutate";
import { SearchCombobox } from "@/components/SearchCombobox";
import { Badge, Button, Card, CardHeader, Field, Input, Modal, PageHeader, Select, Textarea } from "@/components/ui";
import { formatDate } from "@/lib/format";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyRow = Record<string, any>;
const STATUS: Record<string, "slate" | "blue" | "green" | "amber" | "red" | "cyan"> = { planejado:"slate", em_producao:"blue", concluido:"green", bloqueado:"red" };

function iso(date: Date) { return date.toISOString().slice(0, 10); }
function addDays(date: Date, amount: number) { const d = new Date(date); d.setDate(d.getDate() + amount); return d; }

export function ProductionAgenda({ schedules, orders, printers }: { schedules: AnyRow[]; orders: AnyRow[]; printers: AnyRow[] }) {
  const router = useRouter();
  const [start, setStart] = useState(() => new Date());
  const [open, setOpen] = useState(false);
  const [filterPrinter, setFilterPrinter] = useState("");
  const days = useMemo(() => Array.from({ length: 7 }, (_, i) => addDays(start, i)), [start]);
  const filtered = schedules.filter((schedule) => !filterPrinter || String(schedule.printerId) === filterPrinter);
  const plannedMinutes = filtered.filter((schedule) => schedule.status !== "concluido").reduce((sum, schedule) => sum + Number(schedule.estimatedMinutes || 0), 0);
  const availableOrders = orders.filter((order) => !["concluido", "cancelado"].includes(order.status));
  async function updateStatus(id: number, status: string) { await mutate("production-schedules", "update", { status }, id); router.refresh(); }
  return <div>
    <PageHeader eyebrow="Operação" icon="🗓️" title="Agenda de Produção" description="Planeje capacidade por máquina, prazo e duração estimada." action={<Button onClick={() => setOpen(true)}>＋ Agendar produção</Button>} />
    <div className="mb-5 flex flex-wrap items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><Button variant="outline" size="sm" onClick={() => setStart(addDays(start, -7))}>← Semana anterior</Button><Button variant="outline" size="sm" onClick={() => setStart(new Date())}>Hoje</Button><Button variant="outline" size="sm" onClick={() => setStart(addDays(start, 7))}>Próxima semana →</Button><p className="ml-1 text-sm font-bold text-slate-700">{formatDate(days[0])} — {formatDate(days[6])}</p><div className="ml-auto flex items-center gap-2"><span className="text-xs text-slate-400">Máquina</span><Select value={filterPrinter} onChange={(e) => setFilterPrinter(e.target.value)} className="w-52"><option value="">Todas as máquinas</option>{printers.map((printer) => <option key={printer.id} value={printer.id}>{printer.name}</option>)}</Select></div></div>
    <div className="mb-5 grid grid-cols-2 gap-4 lg:grid-cols-4"><Metric label="Horas planejadas" value={`${(plannedMinutes / 60).toFixed(1)}h`} icon="⏱️" /><Metric label="Agendamentos" value={filtered.length} icon="🗓️" /><Metric label="Pedidos aguardando" value={availableOrders.length} icon="📋" /><Metric label="Máquinas ativas" value={printers.filter((p) => p.status === "ativa").length} icon="🖨️" /></div>
    <div className="grid grid-cols-1 gap-3 lg:grid-cols-7">{days.map((day) => { const dayIso = iso(day); const list = filtered.filter((s) => s.scheduledDate === dayIso); const dailyMinutes = list.reduce((sum, s) => sum + Number(s.estimatedMinutes || 0), 0); return <Card key={dayIso} className="min-h-64 overflow-hidden"><CardHeader title={day.toLocaleDateString("pt-BR", { weekday: "short", day: "2-digit", month: "2-digit" })} subtitle={`${(dailyMinutes / 60).toFixed(1)}h planejadas`} /><div className="space-y-2 p-2">{list.map((schedule) => { const printer = printers.find((p) => p.id === schedule.printerId); return <div key={schedule.id} className="rounded-xl border border-slate-200 bg-white p-2.5 shadow-sm"><div className="flex justify-between gap-1"><p className="line-clamp-2 text-xs font-bold text-slate-700">{schedule.title}</p><Badge color={STATUS[schedule.status] || "slate"}>{schedule.status}</Badge></div><p className="mt-1 text-[11px] text-slate-400">🕐 {schedule.startTime} · {schedule.estimatedMinutes} min</p><p className="mt-0.5 truncate text-[11px] text-slate-500">🖨️ {printer?.name || "Sem máquina"}</p><Select value={schedule.status} onChange={(e) => updateStatus(schedule.id, e.target.value)} className="mt-2 h-7 text-[10px]"><option value="planejado">Planejado</option><option value="em_producao">Em produção</option><option value="concluido">Concluído</option><option value="bloqueado">Bloqueado</option></Select></div>; })}{list.length === 0 && <button onClick={() => setOpen(true)} className="w-full rounded-xl border border-dashed border-slate-300 py-4 text-[11px] text-slate-400 hover:border-cyan-300 hover:text-cyan-600">＋ Agendar</button>}</div></Card>; })}</div>
    {open && <ScheduleModal orders={availableOrders} printers={printers} defaultDate={iso(days[0])} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); router.refresh(); }} />}
  </div>;
}
function Metric({ label, value, icon }: { label: string; value: string | number; icon: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xl">{icon}</p><p className="mt-1 text-[11px] font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-xl font-extrabold text-slate-800">{value}</p></div>; }
function ScheduleModal({ orders, printers, defaultDate, onClose, onSaved }: { orders: AnyRow[]; printers: AnyRow[]; defaultDate: string; onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState({ orderId:"", title:"", printerId:"", scheduledDate:defaultDate, startTime:"08:00", estimatedMinutes:"30", notes:"" }); const [saving,setSaving]=useState(false); const set=(key:string,value:string)=>setForm((old)=>({...old,[key]:value})); const orderOptions=orders.map((order)=>({value:String(order.id), label:order.number, detail:`${order.productionStatus} · R$ ${Number(order.total||0).toFixed(2)}`,icon:"📋"})); const printerOptions=printers.filter((printer)=>printer.status==="ativa").map((printer)=>({value:String(printer.id),label:printer.name,detail:printer.maxFormat||printer.buildVolume||"",icon:"🖨️"})); async function save(){if(!form.title)return;setSaving(true);try{await mutate("production-schedules","create",{...form,orderId:form.orderId||null,printerId:form.printerId||null,estimatedMinutes:Number(form.estimatedMinutes||0),status:"planejado"});onSaved();}catch(e){alert(e instanceof Error?e.message:"Erro ao agendar.");}finally{setSaving(false);}} return <Modal open onClose={onClose} icon="🗓️" title="Agendar produção" subtitle="Reserve uma janela de máquina e acompanhe a capacidade."><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Pedido"><SearchCombobox value={form.orderId} onChange={(value)=>{const o=orders.find((item)=>String(item.id)===value);setForm((old)=>({...old,orderId:value,title:old.title||o?.number||""}));}} options={orderOptions} placeholder="Buscar pedido..." emptyLabel="— Agendamento avulso —" /></Field><Field label="Impressora / máquina"><SearchCombobox value={form.printerId} onChange={(value)=>set("printerId",value)} options={printerOptions} placeholder="Buscar máquina..." emptyLabel="— Sem máquina definida —" /></Field><Field label="Título" className="sm:col-span-2"><Input value={form.title} onChange={(e)=>set("title",e.target.value)} placeholder="Ex.: Imprimir 500 tags kraft" /></Field><Field label="Data"><Input type="date" value={form.scheduledDate} onChange={(e)=>set("scheduledDate",e.target.value)} /></Field><Field label="Início"><Input type="time" value={form.startTime} onChange={(e)=>set("startTime",e.target.value)} /></Field><Field label="Duração estimada (min)"><Input type="number" value={form.estimatedMinutes} onChange={(e)=>set("estimatedMinutes",e.target.value)} /></Field><Field label="Observações" className="sm:col-span-2"><Textarea rows={2} value={form.notes} onChange={(e)=>set("notes",e.target.value)} /></Field></div><div className="mt-6 flex justify-end gap-2 border-t border-slate-100 pt-4"><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={save} disabled={saving||!form.title}>{saving?"Agendando...":"Agendar"}</Button></div></Modal>; }
